// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    QuestionItem: typeof import('./src/components/QuestionItem.vue')['default']
    QuestionList: typeof import('./src/components/QuestionList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SongList: typeof import('./src/components/SongList.vue')['default']
    TheBarrage: typeof import('./src/components/TheBarrage.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    ThePlayer: typeof import('./src/components/ThePlayer.vue')['default']
    TheShare: typeof import('./src/components/TheShare.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
